export const fetchStoriesFromFirebase = async () => [];
export const fetchUsersFromFirebase = async () => [];
export const fetchNotificationsFromFirebase = async () => [];
export const fetchMessagesFromFirebase = async () => [];
export const fetchReportsFromFirebase = async () => [];
export const fetchForumTopicsFromFirebase = async () => [];
export const fetchParagraphCommentsFromFirebase = async () => [];
export const saveStoryToFirebase = async () => {};
export const saveUserToFirebase = async () => {};
export const saveNotificationToFirebase = async () => {};
export const saveMessageToFirebase = async () => {};
export const saveReportToFirebase = async () => {};
export const saveForumTopicToFirebase = async () => {};
export const saveParagraphCommentToFirebase = async () => {};
export const saveCommentToFirebase = async () => {};
export const deleteStoryFromFirebase = async () => {};
export const deleteUserFromFirebase = async () => {};
export const deleteForumTopicFromFirebase = async () => {};
export const deleteParagraphCommentFromFirebase = async () => {};
export const deleteReportFromFirebase = async () => {};
export const deleteCommentFromFirebase = async () => {};
export const sendCommentEmailNotification = async () => {};
export const sendMessageEmailNotification = async () => {};
export const firebaseGoogleLoginUser = async () => ({ success: false });
export const firebaseLoginUser = async () => ({ success: false });
export const firebaseRegisterUser = async () => ({ success: false });
export const firebasePasswordReset = async () => ({ success: false });
export const firebaseLogoutUser = async () => {};
export const auth = {};
export const db = {};
